import React from 'react';
import { ChevronLeft, FileText, ShieldCheck, AlertTriangle, Copyright } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const Protocols: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-[calc(100vh-64px)] w-full flex justify-center p-4 md:p-8 relative overflow-hidden">
      {/* Dynamic Background Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
         <div className="absolute top-[-10%] left-[50%] -translate-x-1/2 w-[60%] h-[40%] bg-neon/5 rounded-full blur-[120px] animate-pulse-slow"></div>
      </div>

      <div className="relative z-10 w-full max-w-4xl bg-[#0A0A0B]/80 backdrop-blur-2xl border border-white/10 rounded-3xl overflow-hidden shadow-[0_0_50px_rgba(0,0,0,0.5)] flex flex-col h-[85vh]">
        
        {/* Decorative Grid Overlay */}
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none"></div>
        <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:40px_40px] pointer-events-none"></div>

        {/* Header */}
        <div className="p-8 border-b border-white/5 bg-white/5 relative z-10">
             <button 
                onClick={() => navigate('/login')}
                className="flex items-center gap-2 text-xs font-mono text-gray-500 hover:text-white transition-colors mb-4"
            >
                <ChevronLeft className="w-4 h-4" /> Return to Access Point
            </button>

            <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-neon/10 rounded-xl border border-neon/30 flex items-center justify-center">
                    <FileText className="w-6 h-6 text-neon" />
                </div>
                <div>
                    <h2 className="text-2xl md:text-3xl font-bold text-white tracking-tight">Operational Protocols</h2>
                    <p className="text-gray-400 text-xs font-mono mt-1">Version 2.4.0 // Last Updated: 2024-10-14</p>
                </div>
            </div>
        </div>

        {/* Scrollable Content */}
        <div className="flex-grow overflow-y-auto p-8 space-y-8 scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-transparent">
            
            <section className="space-y-3">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="text-neon font-mono">01.</span> Licensing Architecture
                </h3>
                <div className="p-4 bg-white/5 rounded-lg border border-white/5 text-sm text-gray-400 leading-relaxed font-mono">
                    <p className="mb-2">All audio assets acquired through BeatWave are subject to non-exclusive licensing agreements unless "Exclusive Rights" are explicitly purchased.</p>
                    <ul className="list-disc pl-5 space-y-1 opacity-80">
                        <li><strong className="text-gray-300">Basic Lease (MP3):</strong> Limited to 50,000 streams. Non-profit use prioritized.</li>
                        <li><strong className="text-gray-300">Premium Lease (WAV):</strong> Up to 500,000 streams. Commercial monetization authorized.</li>
                        <li><strong className="text-gray-300">Unlimited:</strong> No caps on streaming or distribution. Broadcast rights included.</li>
                    </ul>
                </div>
            </section>

            <section className="space-y-3">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="text-neon font-mono">02.</span> Transaction Finality
                </h3>
                <div className="p-4 bg-white/5 rounded-lg border border-white/5 text-sm text-gray-400 leading-relaxed font-mono">
                    <div className="flex items-start gap-3">
                        <AlertTriangle className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
                        <p>
                            Due to the digital nature of audio signals and stems, <strong className="text-white">all transactions are final and non-refundable</strong> once the download link has been generated by the server. Ensure compatibility and satisfaction via the preview player before initializing purchase.
                        </p>
                    </div>
                </div>
            </section>

            <section className="space-y-3">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="text-neon font-mono">03.</span> AI & Derivative Works
                </h3>
                <div className="p-4 bg-white/5 rounded-lg border border-white/5 text-sm text-gray-400 leading-relaxed font-mono">
                    <p>
                        Utilization of BeatWave assets for the training of Generative AI models, neural networks, or automated beat-making algorithms is <strong className="text-red-400">strictly prohibited</strong>. Producers retain moral rights against unauthorized synthetic reproduction of their sonic signature.
                    </p>
                </div>
            </section>

            <section className="space-y-3">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="text-neon font-mono">04.</span> Content ID & Copyright
                </h3>
                <div className="p-4 bg-white/5 rounded-lg border border-white/5 text-sm text-gray-400 leading-relaxed font-mono">
                    <p className="mb-2">Purchasers of non-exclusive licenses are forbidden from registering the derivative work (your song) with Content ID systems (e.g., YouTube Content ID, Facebook Rights Manager).</p>
                    <div className="flex items-center gap-2 text-xs text-gray-500 mt-2">
                        <Copyright className="w-3 h-3" />
                        <span>Violation of this protocol will result in immediate license termination.</span>
                    </div>
                </div>
            </section>

             <section className="space-y-3">
                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <span className="text-neon font-mono">05.</span> Unauthorized Distribution
                </h3>
                <div className="p-4 bg-white/5 rounded-lg border border-white/5 text-sm text-gray-400 leading-relaxed font-mono">
                    <p>
                        Redistribution of raw beat files, stems, or sound kits to third-party marketplaces, file-sharing nodes, or torrent swarms constitutes a breach of contract. Legal algorithms will be deployed to enforce copyright compliance.
                    </p>
                </div>
            </section>

            <div className="h-10"></div> {/* Spacer */}
        </div>
      </div>
    </div>
  );
};